Jinstagram/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Sub
from content.views import Community, UploadFeed
from .settings import MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('content.urls')),
    path('user/', include('user.urls'))
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path,include
from nuribom import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nuribom/', include('nuribom.urls')),
]

content/urls.py
from django.urls import path
from .views import DeleteVolunteer, SearchResult, UploadFeed, Profile,\
    Community, UploadReply, ToggleLike, ToggleBookmark, DeleteFeed, createVolunteerITem, \
        Main, Search, Follow, Participate, NotParticipate, feed_detail, volunteer_detail
from . import views


app_name = 'content'

urlpatterns = [
    path('', Main.as_view(), name="main"),
    path('community', Community.as_view(), name="community"),
    path('profile', Profile.as_view(), name="profile"),
    path('search', Search.as_view(), name="search"),
    path('search_result',  SearchResult.as_view(), name="search_result"),

    path('createvolunteer', createVolunteerITem.as_view(), name="create_volunteer"),
    path('deletevolunteer', DeleteVolunteer.as_view()),

    path('delete_feed', DeleteFeed.as_view()),
    path('upload_feed', UploadFeed.as_view()),
    path('reply_feed', UploadReply.as_view()),
    path('like_feed', ToggleLike.as_view()),
    path('feed_detail/<int:feed_id>', feed_detail),
    path('volunteer_detail/<int:feed_id>', volunteer_detail),

    path('test', Follow.as_view(), name="test"),

    path('bookmark_volunteer', ToggleBookmark.as_view()),
    path('participate_volunteer', Participate.as_view()),
    path('not_participate_volunteer', NotParticipate.as_view()),
]

user/urls.py
from django.urls import path
from .views import Join, Login, LogOut, UploadProfile

urlpatterns = [
    path('join', Join.as_view()),
    path('login', Login.as_view()),
    path('logout', LogOut.as_view()),
    path('profile/upload', UploadProfile.as_view())
]

content/models.py
from django.db import models
from user.models import User
import datetime

# Create your models here.
class Feed(models.Model):
    content = models.TextField()    # 글내용
    image = models.TextField()  # 피드 이미지
    email = models.EmailField(default='')     # 글쓴이
    create_time = models.DateTimeField(default=datetime.datetime.now())


class Like(models.Model):
    feed_id = models.IntegerField(default=0)
    email = models.EmailField(default='')
    is_like = models.BooleanField(default=True)


class Reply(models.Model):
    feed_id = models.IntegerField(default=0)
    email = models.EmailField(default='')
    reply_content = models.TextField()


class Bookmark(models.Model):
    feed_id = models.IntegerField(default=0)
    email = models.EmailField(default='')
    is_marked = models.BooleanField(default=True)

class VolunteerItem(models.Model):
    admin = models.ForeignKey(User,on_delete = models.CASCADE)
    title = models.TextField(default='')
    volunteer_image = models.TextField()
    region = models.TextField() 
    participant = models.IntegerField(default = 0)
    description = models.TextField()
    lat = models.DecimalField(max_digits = 10,decimal_places= 6, default=0)
    lng = models.DecimalField(max_digits = 10,decimal_places= 6, default=0)
    date = models.DateField(default = None)
    start_time = models.TimeField(default = None)
    end_time = models.TimeField(default = None)
    admit_time = models.IntegerField(default = 0)
    done = models.BooleanField(default=False)
    create_time = models.DateTimeField(default=datetime.datetime.now())

class ParticipateItems(models.Model):
    grant = models.BooleanField(default=False)
    volunteerItem = models.ForeignKey(VolunteerItem, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

content/views.py
from uuid import uuid4
from django.shortcuts import render, redirect
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Feed, ParticipateItems, Reply, Like, Bookmark, VolunteerItem
from user.models import User
import os
from Jinstagram.settings import MEDIA_ROOT
from django.db.models import Q
from content.models import VolunteerItem
from django.views.decorators.csrf import csrf_exempt
from . import config
import math
import collections
from django.shortcuts import get_object_or_404

class Community(APIView):
    def get(self, request):
        email = request.session.get('email', None)

        if email is None:
            return render(request, "user/login.html")

        mainuser = User.objects.filter(email=email).first()

        if mainuser is None:
            return render(request, "user/login.html")

        feed_object_list = Feed.objects.all().order_by('-id')  # select  * from content_feed;
        feed_list = []

        volunteer_object_list = VolunteerItem.objects.all().order_by('-id')
        volunteer_list = []

        for feed in feed_object_list:
            user = User.objects.filter(email=feed.email).first()
            reply_object_list = Reply.objects.filter(feed_id=feed.id)
            reply_list = []
            for reply in reply_object_list:
                user = User.objects.filter(email=reply.email).first()
                reply_list.append(dict(reply_content=reply.reply_content,nickname=user.nickname))
            like_count=Like.objects.filter(feed_id=feed.id, is_like=True).count()
            is_liked=Like.objects.filter(feed_id=feed.id, email=email, is_like=True).exists()
            feed_list.append(dict(id=feed.id,
                                image=feed.image,
                                content=feed.content,
                                like_count=like_count,
                                profile_image=user.profile_image,
                                nickname=user.nickname,
                                reply_list=reply_list,
                                is_liked=is_liked,
                                create_time = feed.create_time
                                ))

        for volunteer in volunteer_object_list:
            is_marked=Bookmark.objects.filter(feed_id=volunteer.id, email=email, is_marked=True).exists()
            participateitems = ParticipateItems.objects.filter(volunteerItem_id =volunteer.id).all() # 참여 신청 리스트 중 해당 봉사에 해당하는 것들
            participateitem = participateitems.filter(user_id = mainuser.id).first() # 그 중에서 현재 로그인된 유저가 신청한 것들
            isparticipated = False
            grant = False
            if participateitem:
                grant = participateitem.grant
                isparticipated = True
            print(isparticipated)

            volunteer_list.append(dict(id=volunteer.id,
                                image=volunteer.volunteer_image,
                                region=volunteer.region,
                                participant=volunteer.participant,
                                admin = volunteer.admin,
                                isparticipated = isparticipated,
                                grant = grant,
                                is_marked = is_marked,
                                create_time = volunteer.create_time
                                ))



        return render(request, "content/community.html", context=dict(feeds=feed_list, 
                                                                    volunteers = volunteer_list,
                                                                    mainuser=mainuser))

class Participate(APIView):
    def post(self, request):
        email = request.session.get('email', None)
        mainuser = User.objects.filter(email=email).first()

        volunteer_id = request.data.get('volunteer_id')
        participated_item = VolunteerItem.objects.filter(id=volunteer_id).first()

        ParticipateItems.objects.create(
            user_id = mainuser.id,
            volunteerItem_id = participated_item.id,
            grant=0
        )
        participated_item.participant-=1
        participated_item.save()

        return Response(200)

class NotParticipate(APIView):
    def delete(self, request):
        email = request.session.get('email', None)
        mainuser = User.objects.filter(email=email).first()

        volunteer_id = request.data.get('volunteer_id')
        participated_item = VolunteerItem.objects.filter(id=volunteer_id).first()
        print(participated_item.participant)
        participated_item.participant = participated_item.participant + 1
        participated_item.save()

        remove_item = ParticipateItems.objects.filter(Q(user_id = mainuser.id) & Q(volunteerItem_id = participated_item.id))
        remove_item.delete()

        return Response(200)

class UploadFeed(APIView):
    def post(self, request):

        # 일단 파일 불러와
        file = request.FILES['file']

        uuid_name = uuid4().hex
        save_path = os.path.join(MEDIA_ROOT, uuid_name)

        with open(save_path, 'wb+') as destination:
            for chunk in file.chunks():
                destination.write(chunk)

        asdf = uuid_name
        content123 = request.data.get('content')
        email = request.session.get('email', None)

        Feed.objects.create(image=asdf, content=content123, email=email)

        return Response(status=200)

class DeleteFeed(APIView):
    def delete(self, request):
        feed_id = request.data.get('feed_id', None)
        feed = Feed.objects.filter(id=feed_id).first()
        feed.delete()
        return Response(status=200)


class Profile(APIView):
    def get(self, request):
        email = request.session.get('email', None)

        if email is None:
            return render(request, "user/login.html")

        mainuser = User.objects.filter(email=email).first()

        if mainuser is None:
            return render(request, "user/login.html")

        participate_list=[]
        participated_user_list=[]


        if mainuser.role =='Admin':
            created_list = VolunteerItem.objects.filter(admin=mainuser).all()
            for item in created_list: # 봉사 기관자가 생성한 voluteeritem에 대해서
                participated_created_list = ParticipateItems.objects.filter(volunteerItem_id = item.id).all() # 신청된 것들 선발
                if participated_created_list: #만약 신청 받은 것이 있다면
                    for participated_item in participated_created_list:
                        user = User.objects.filter(id = participated_item.user_id).first()
                        isgranted = participated_item.grant
                        participate_list.append([item, user, isgranted])
                    print(participate_list)
        else:
            participated_list =[]
            participated_list.append(ParticipateItems.objects.filter(user_id = mainuser.id).all()) # 현재 유저가 신청한 volunteeritem들
            for participated_item in participated_list:
                if(participated_item):
                    participate_item = VolunteerItem.objects.filter(id = participated_item.first().volunteerItem_id) # 직접 volunteeritem 객체 배열에 넣어주기
                    if participate_item:
                        grant = ParticipateItems.objects.filter(volunteerItem_id = participate_item.first().id).first().grant # 해당 봉사의 승인 여부
                        print(grant)
                        participate_list.append([participate_item, grant])
                    continue

        feed_list = Feed.objects.filter(email=email)
        like_list = list(Like.objects.filter(email=email, is_like=True).values_list('feed_id', flat=True))
        like_feed_list = Feed.objects.filter(id__in=like_list)
        bookmark_list = list(Bookmark.objects.filter(email=email, is_marked=True).values_list('feed_id', flat=True))
        bookmark_volunteer_list = VolunteerItem.objects.filter(id__in=bookmark_list)
        return render(request, 'content/profile.html', context=dict(feed_list=feed_list,
                                                                    like_feed_list=like_feed_list,
                                                                    bookmark_volunteer_list=bookmark_volunteer_list,
                                                                    mainuser = mainuser,
                                                                    participate_list=participate_list,
                                                                ))

    def post(self, request):
        user = request.data.get('user')
        item = request.data.get('item')
        time = request.data.get('admit_time')

        granted_user = User.objects.filter(id=user).first()
        granted_user.sum_time += int(time)

        if granted_user.sum_time >=10 :
            granted_user.ranking = 'Flower'
        elif granted_user.sum_time >=8 :
            granted_user.ranking = 'Tree'
        elif granted_user.sum_time >=6 :
            granted_user.ranking = 'Seedling'
        elif granted_user.sum_time >=4 :
            granted_user.ranking = 'Sprout'

        granted_user.save()

        granted_item = ParticipateItems.objects.filter(volunteerItem_id=item).first()
        granted_item.grant = 1
        granted_item.save()

        remove_item = ParticipateItems.objects.filter(Q(user_id = user) & Q(volunteerItem_id = item))
        remove_item.delete()


        return Response(status=200)


class UploadReply(APIView):
    def post(self, request):
        feed_id = request.data.get('feed_id', None)
        reply_content = request.data.get('reply_content', None)
        email = request.session.get('email', None)

        Reply.objects.create(feed_id=feed_id, reply_content=reply_content, email=email)

        return Response(status=200)


class ToggleLike(APIView):
    def post(self, request):
        feed_id = request.data.get('feed_id', None)

templates/content/createVolunteerItem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'createVolunterItem.css' %}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Google Icon -->
    <link
            href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
            rel="stylesheet">
    <!-- Jquery -->
    <script src="http://code.jquery.com/jquery-latest.min.js"></script> 

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
    <title>createVolunteerItem</title>
   
     <!--주소 검색 api-->
     <script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
    <!-- services 라이브러리 불러오기 -->
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=73a7bf3da2a6472e3d0ca0cd49ccb6c3&libraries=services"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="position: fixed;width: 100%; z-index:10;">
    <div class="container-fluid" style="justify-content: space-between;flex-wrap: nowrap; min-width: 1000px">
        <a class="navbar-brand" href={% url "content:main"%}><img style="width: 100px"
                                                src="https://www.instagram.com/static/images/web/mobile_nav_type_logo-2x.png/1b47f9d0e595.png">
        </a>
        <div style="display: flex">
            <a href={% url "content:community"%} style="color: black">커뮤니티</a>
            &nbsp;  &nbsp;  &nbsp; 
            <a href={% url "content:search"%} style="color: black">봉사 검색</a>
            &nbsp;  &nbsp;  &nbsp; 
            {%if mainuser.role == 'Admin'%}
            <a href={% url "content:create_volunteer"%} style="color: black">봉사 추가</a>
            &nbsp;  &nbsp;  &nbsp; 
            {%endif%}
            <span id="nav_bar_add_box" class="material-icons-outlined" style="padding-right: 10px">add_box</span>
            &nbsp;  &nbsp;  &nbsp; 
            <div class="dropdown">
                <a href="#" role="button" id="dropdownMenuLink"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    <div class="box" style="width: 40px; height: 40px">
                        <img class="profile"
                            src="{% get_media_prefix %}{{ mainuser.profile_image }}">
                    </div>
                </a>

                <ul class="dropdown-menu" style="left:-158px" aria-labelledby="dropdownMenuLink">
                    <li><a class="dropdown-item" href="/main/profile">프로필</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="/user/logout">로그아웃</a></li>
                </ul>
            </div>
        </div>
    </div>
</nav>
    <br/><br/><br/>
    <div style="width:50%; margin: 0 auto;">
        <div class="input-group mb-3" style="width:100%">
        <input type="text" disabled id="sample5_address" class="form-control" placeholder="주소"
        aria-describedby="button-addon2">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="button-addon2" onclick="sample5_execDaumPostcode()">주소 검색<br>
            <div id="map" style="width:300px;height:300px;margin-top:10px;display:none"></div>
        </div>    
        </div>
        <div class="input-group mb-3" style="width:100%">
            <span class="input-group-text" id="basic-addon1">제목</span>
            <input type="text" id="title" class="form-control" aria-describedby="basic-addon1">
        </div>
       <div class="input-group mb-3" style="width:100%">
            <span class="input-group-text" id="basic-addon1"></span>
            <input type="file" class="custom-file-input file form-control" id="file">
        </div>
        <div class="input-group mb-3" style="width:100%">
            <span class="input-group-text" id="basic-addon1">인원</span>
            <input type="number" min="1" id="participant" class="form-control" aria-describedby="basic-addon1">
        </div>
        <div class="input-group">
            <span class="input-group-text">설명</span>
            <textarea class="form control" id="description" type="text" style="width:92%"></textarea>
        </div>
        <br>
        <div class="input-group mb-3" style="width:100%">
            <span class="input-group-text" id="basic-addon1">날짜 선택</span>
            <input id="date" type="date" class="form-control" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3" style="width:100%">
            <span class="input-group-text" id="basic-addon1">시작 시간</span>
            <input id="start_time" type="time" class="form-control" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3" style="width:100%">
            <span class="input-group-text" id="basic-addon1">종료 시간</span>
            <input id="end_time" type="time" class="form-control" aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3" style="width:100%">
            <span class="input-group-text" id="basic-addon1">봉사 인정 시간</span>
            <input id="admit_time" type="number" class="form-control" aria-describedby="basic-addon1">
        </div>
        <div><input style="display:none" id="user" type="text" value={{mainuser.email}}/></div>
        <br>
        <div class="input-group mb-3" style="width: 100px; margin: 0 auto;">
            <button class="btn btn-outline-secondary" type="submit" id="submit">등록</button>
        </div>
    </div> 
</body>
</html>

<form>
<script>

    var mapContainer = document.getElementById('map'), // 지도를 표시할 div
    mapOption = {
        center: new daum.maps.LatLng(37.537187, 127.005476), // 지도의 중심좌표
        level: 5 // 지도의 확대 레벨
    };

//지도를 미리 생성
var map = new daum.maps.Map(mapContainer, mapOption);
//주소-좌표 변환 객체를 생성
var geocoder = new daum.maps.services.Geocoder();
//마커를 미리 생성
var marker = new daum.maps.Marker({
    position: new daum.maps.LatLng(37.537187, 127.005476),
    map: map
});

let lat=0;
let lng=0;

function sample5_execDaumPostcode() {
    new daum.Postcode({
        oncomplete: function(data) {
            var addr = data.address; // 최종 주소 변수

            // 주소 정보를 해당 필드에 넣는다.
            document.getElementById("sample5_address").value = addr;
            // 주소로 상세 정보를 검색
            geocoder.addressSearch(data.address, function(results, status) {
                // 정상적으로 검색이 완료됐으면
                if (status === daum.maps.services.Status.OK) {

                    var result = results[0]; //첫번째 결과의 값을 활용

                    // 해당 주소에 대한 좌표를 받아서
                    var coords = new daum.maps.LatLng(result.y, result.x);

                    lat = result.y
                    lng = result.x

                    // 지도를 보여준다.
                    mapContainer.style.display = "block";
                    map.relayout();
                    // 지도 중심을 변경한다.
                    map.setCenter(coords);
                    // 마커를 결과값으로 받은 위치로 옮긴다.
                    marker.setPosition(coords)
                }
            });
        }
    }).open();
}


$("#submit").click(function user_update() {
    let file = document.getElementById("file").files[0]
    let region = document.getElementById("sample5_address").value;
    let participant = document.getElementById("participant").value;
    let description = document.getElementById("description").value;
    let date = document.getElementById("date").value;
    let start_time = document.getElementById("start_time").value;
    let end_time = document.getElementById("end_time").value;
    let admit_time = document.getElementById("admit_time").value;
    let email = document.getElementById("user").value.slice(0, -1);
    let title = document.getElementById("title").value;

    let form_data = new FormData()

    form_data.append("file_give", file)
    form_data.append("region", region)
    form_data.append("participant", participant)
    form_data.append("description", description)
    form_data.append("date", date)
    form_data.append("start_time", start_time)
    form_data.append("end_time", end_time)
    form_data.append("admit_time", admit_time)
    form_data.append("email", email)
    form_data.append("title", title)
    form_data.append("lat", lat)
    form_data.append("lng", lng)

    //사진이 들어가지 않았을 때
$.ajax({
        type: "POST",
        url: "/main/createvolunteer",
        data: form_data,
        cache: false,
        contentType: false,
        processData: false,
        success: function (response) {
            alert("봉사가 등록되었습니다.")
            location.replace("/main/community");
        },
    })
}
);
</script>

templates/content/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
      #grid{
          display:grid;
          grid-template-columns: 1fr 1fr 1fr;
          
          
          margin-top:40px;
          margin-bottom:40px;
          margin-left: 60px;
          margin-right: 60px;          
      }
      .slide{
          width:600px;
      }
    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>누리봄</title>
    {% load static %}
     <!-- Bootstrap CSS -->
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
     integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Google Icon -->
    <link
       href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
       rel="stylesheet">

    
</head>
<nav class="navbar navbar-expand-lg navbar-light " style="position: fixed;width: 100%; display:block; z-index:10; background-color:rgba(255,255,255,0.5);">
  <div class="container-fluid" style="justify-content:center;">
      <a class="navbar-brand" href={% url "content:main"%}>
        <img style="display:block;align-content:center;width: 100px;margin:0 auto;"
        src="https://www.instagram.com/static/images/web/mobile_nav_type_logo-2x.png/1b47f9d0e595.png">
      </a>
      
  </div>
</nav>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <div><img src="../media/메인페이지.jpg" style="width:100%"></div>
    
        <div id="grid">
            <span align="center" onClick="location.href='{% url "content:profile"%}'" style="width:auto;">
                <img src="https://img.icons8.com/fluency-systems-regular/344/users-settings.png" width="70" alt="" style="cursor:pointer;">
                <br><span role="button" style="font-size:20pt;">My page</span>
            </span>
            <span align="center" onClick="location.href='{% url "content:search"%}'" style="width:auto;">
                <img src="https://1717271001-files.gitbook.io/~/files/v0/b/gitbook-legacy-files/o/assets%2F-L_Wo7SRUvbKJuPojzzZ%2F-Lnc5yjngpz9pVF2baNZ%2F-Lnc91zireWvsZ421Uon%2Fimage.png?alt=media&token=8378dd77-6783-4ce5-9f4e-5217e284a3d3" width="70" alt="" style="cursor:pointer;">
                <br><span role="button" style="font-size:20pt">Search</span>
            </span>
            <span align="center" onClick="location.href='{% url "content:community"%}'" style="width:auto;">
                <img src="https://img.icons8.com/ios/2x/groups.png" width="70" alt="" style="cursor:pointer;">
                <br><span role="button" style="font-size:20pt;">Community</span>
            </span>
        </div>
        <div style="width:100%; height: auto; background-color:#D9D9D9;padding:30px; display:flex;justify-content:space-around;">
          <div>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/ugxneQ8Uiu0" title="YouTube video player" frameborder="0"
             allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <div style="margin-left:20px;">  
            <div style="margin-bottom:20px;text-align:center;">오늘의 봉사 지식</div>
              <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel" style="">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img class="slide" src="../media/장애인주차구역.png" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img class="slide" src="../media/점자블럭.png" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img class="slide" src="../media/시각장애인.png" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img class="slide" src="../media/청각장애인.png" class="d-block w-100" alt="...">
                  </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
          </div>
        </div>
        
    
</body>

</html>

templates/content/searchbox.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>search</title>
</head>
<!--상단바-->
<body>
    <div style="width:100%; height: 200px; background-color:#B0FDB3;text-align:center;">
        <input id="searchbox" type="search" placeholder="봉사기관/봉사명을 입력하세요" style="width:100px;"></input>
        <button id="search_button" class="button">
            <img src="https://img.icons8.com/external-flat-icons-inmotus-design/344/external-Search-round-mobile-ui-set-flat-icons-inmotus-design-2.png"
            style="width: 67px;height: 67px;">
        </button>
    </div>
</body>
</html>